# -*- coding: utf-8 -*-
"""bootcamp.Favrioute food..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ei3fRxRmpelxvpNLQMlmG-5Kr2MkjCvL
"""

# Favorite Food Program

food = input("What is your favorite food? ")
drink = input("What is your favorite drink? ")
dessert = input("What is your favorite dessert? ")

print("\n===== Favorite Food =====")
print("Food:", food)
print("Drink:", drink)
print("Dessert:", dessert)