# -*- coding: utf-8 -*-
"""bootcamp.Student Information.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ta7pQkhi-kxBy_sDXpBHgR_phLZYls_L
"""

# Student Information Program

name = input("Enter your name: ")
age = input("Enter your age: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
semester = input("Enter your semester: ")

print("\n===== Student Information =====")
print("Name:", name)
print("Age:", age)
print("University:", university)
print("Department:", department)
print("Semester:", semester)