# -*- coding: utf-8 -*-
"""bootcamp.Favorite Movie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZ5VnFztPCWSJnIyPjyXBGu4zEVAj5Z4
"""

# Favorite Movie Program

movie = input("What is your favorite movie? ")
actor = input("Who is your favorite actor? ")
year = input("What year was the movie released? ")

print("\n===== Favorite Movie =====")
print("Movie:", movie)
print("Favorite Actor:", actor)
print("Release Year:", year)