# -*- coding: utf-8 -*-
"""bootcamp.Dream Job.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwv4e6nRjxHOi9KvtVyJPpBtGDVw1xqj
"""

# Dream Job Program

job = input("What is your dream job? ")
company = input("Which company do you want to work for? ")
country = input("Which country do you want to work in? ")

print("\n===== Dream Job =====")
print("Dream Job:", job)
print("Company:", company)
print("Country:", country)